gitlab:
  user_initpassword: "password1234"
  accesstoken: "" 
  gitlabDomain: "https://gitlab.choilab.xyz/api/v4/"

  group_member_default_expires: "2022-01-01"

  root_appId:
    python: 1
    springboot: 2
    appofapps: ''
  
jenkins:
  access_token: ""
  host: "https://jenkins.choilab.xyz/"
  admin_user: "admin"

  createjob:
    job_template: "job_templatev1.xml"
    
helm:
  root_Id:
    springboot: 35
  
  common_helm_groupId: 85
  default_resources:
    cpu: "0.5"
    memeory: "512Mi"