apiVersion: v1
kind: Service
metadata:
  name: jmeter-server
  labels:
    jmeter_role: server
spec:
  clusterIP: None
  ports:
    - port: 1099
      name: first
      targetPort: 1099
    - port: 50000
      name: second
      targetPort: 50000
  selector:
    jmeter_role: server