apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: backend-tg-config
spec:
  targetReference:
    name: backend
  defaultConfiguration:
    targetType: ip
    protocol: HTTP
    healthCheckConfig:
      healthCheckProtocol: HTTP
      healthCheckPath: /
      healthCheckPort: "3000"
      healthCheckInterval: 30
      healthCheckTimeout: 5
      healthyThresholdCount: 2
      unhealthyThresholdCount: 2
