apiVersion: v1
kind: Service
metadata:
  name: heap-test-equal
  namespace: heap-test
spec:
  type: NodePort
  selector:
    app: heap-test
    variant: xms-equal-xmx
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
