apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-canary
spec:
  parentRefs:
  - name: eg
  hostnames:
  - "www.example.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - group: ""
      kind: Service
      name: backend-v1
      port: 3000
      weight: 50  # 50% to v1
    - group: ""
      kind: Service
      name: backend-v2
      port: 3000
      weight: 50  # 50% to v2
