kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: pr-preview
nodes:
- role: control-plane
  image: kindest/node:v1.30.4
  extraPortMappings:
  # ArgoCD server nodePort HTTP
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP
  # ArgoCD server nodePort HTTPS
  - containerPort: 30443
    hostPort: 30443
    protocol: TCP
